### ISSUE TITLE
Change ETH cap on Early Bird Phase 1

### ISSUE THREAD

**Issue by ted-oneill** [NarrativeNetwork/tokensale-smartcontract#1]
I'd like to change the hard cap in Early Bird phase from 6500 ETH to 9000 ETH.

**Comment by win2win** [comment]
adjusted

**Comment by brianlenz** [comment]
Hi @win2win, I'm not seeing those changes in git yet. Do you need to push your changes?

**Comment by brianlenz** [comment]
I see this change now in the push you just did, thanks.
