### ISSUE TITLE
Remove minimum contribution for main sale

### ISSUE THREAD

**Issue by brianlenz** [NarrativeNetwork/tokensale-smartcontract#3]
We don't want a minimum contribution for the main sale. I see the contract sets the minimum to 1 ether currently. Can you change so that there is no minimum (0), please, @win2win?

**Comment by win2win** [comment]
I think you need something than. 
Currently we have this check which is common for all the sales. 

require (msg.value >= minInvestment); 

Although this doesn't have damaging effects, sending 0 eth would be possible if we made minimum contribution = 0 

At least we should have  0.1 eth.

**Comment by brianlenz** [comment]
Thanks, @win2win, that makes sense.

@ted-oneill, would you be OK with 0.1 eth as the minimum for the main sale? That seems reasonable to me. If we go with that, perhaps we should change our "No minimum" wording to 0.1 ETH (or whatever the limit is) for total clarity.

**Comment by brianlenz** [comment]
OK, let's go with 0.1, please, @win2win. Thanks!

**Comment by win2win** [comment]
Done

**Comment by brianlenz** [comment]
Thanks, Bogdan!
