### ISSUE TITLE
Update refundNonCompliant to handle pre-close refunds

### ISSUE THREAD

**Issue by brianlenz** [NarrativeNetwork/tokensale-smartcontract#4]
@win2win, we've discussed the `refundNonCompliant` scenario a bit more internally, and we would like to make a tweak to how refunds are handled prior to closing the sale.

The current behavior works just fine for refunds during early bird and pre-sale, since the `dollarPerEtherRatio` hasn't been set yet. Thus, there is no token impact to the refund.

The issue we see is that refunds during the main sale will "lock" the refunded tokens up by assigning them to the company instead of putting them back into the pool.

Thus, we would like to update the `refundNonCompliant` to put the tokens back into the pool for refunds during the main sale. For refunds post-sale, we can continue to do what we are doing now: assign the refunded tokens to the company.

Thus, I think this:

```
companyTokensInitial += tokensToSend;
```

would just need to be updated to:

```
if(dateICOEnded == 0) {
    totalTokensSold -= tokensToSend;
} else {
    companyTokensInitial += tokensToSend;
}
```

Does this make sense to you? Do you see any flaws with the approach?

Thanks!

**Comment by win2win** [comment]
There is no flow here. This will work.

**Comment by brianlenz** [comment]
Thanks, Bogdan!
